language: java
jdk: oraclejdk8
sudo: false # faster builds
notifications:
    email:
      - k.mucik@e-strix.pl
before_install:
  - chmod +x gradlew
  - pip install --user codecov
script:
  - ./gradlew clean test codeCoverageReport sonarqube -Dsonar.host.url=https:/sonarqube.com -Dsonar.login=$SONAR_TOKEN
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
after_success:
  - codecov
